### ISSUE TITLE
Move caption to below the main SVG.

### ISSUE THREAD

**Issue by breck7** [breck7/notation.scroll.pub#14]
People are right that the caption on the left should be below the image, not the links.

**Comment by plin0009** [comment]
Hi, I'm interested in working on this!

**Comment by breck7** [comment]
Great! Looks like I just made the current page quick and dirty. So may just be a matter of moving a div tag around, perhaps with some css adjustments if needed.

**Comment by breck7** [comment]
Looks like it works! Perhaps it would look better if the text were left aligned now, and maybe had a fixed height, so the content below does not jump around as someone clicks on the links.

**Comment by breck7** [comment]
Fixed! Thanks @plin0009
